### ISSUE TITLE
Can't run d365 create webresource

### ISSUE THREAD

**Issue by aslanovsergey** [derekfinlinson/d365-cli#1]
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'cross-spawn'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Sergey\AppData\Roaming\npm\node_modules\d365-cli\dist\commands\create\webresource.js:14:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by derekfinlinson** [comment]
I had cross-spawn in devdependencies instead of dependencies. Install the latest version and it should work.
